<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    use RecordsActivity;

    protected $guarded = ['id'];
    protected $with = ['customer', 'orderItems', 'worker', 'user'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub


    }




    public function company()
    {
        return $this->belongsTo(Company::class);
    }

    public function worker()
    {
        return $this->belongsTo(Worker::class);
    }

    public function orderItems()
    {
        return $this->hasMany(OrderItem::class);
    }

    public function user() {
        return $this->belongsTo(User::class);
    }

    public function saveOrderItems($data) {

        $this->orderItems()->create($data);

    }





}
